// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxwohoM6zhyxt4l9EpvW9cs8-0LZcsftM',
    appId: '1:1040090871809:web:44c4a3cb42cf756d32e800',
    messagingSenderId: '1040090871809',
    projectId: 'widget-of-the-week',
    authDomain: 'widget-of-the-week.firebaseapp.com',
    storageBucket: 'widget-of-the-week.appspot.com',
    measurementId: 'G-R1SJEGNXWX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDu9BLb5Q5rXNP0M0TJHnB_lelEiGeqNWE',
    appId: '1:1040090871809:android:823ed0be6cc842c632e800',
    messagingSenderId: '1040090871809',
    projectId: 'widget-of-the-week',
    storageBucket: 'widget-of-the-week.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZVWzYslbPHTNK3ItWpzzh7lUiNNwOf14',
    appId: '1:1040090871809:ios:68bcc9e836e59cea32e800',
    messagingSenderId: '1040090871809',
    projectId: 'widget-of-the-week',
    storageBucket: 'widget-of-the-week.appspot.com',
    iosBundleId: 'com.example.widgetOfTheWeek',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZVWzYslbPHTNK3ItWpzzh7lUiNNwOf14',
    appId: '1:1040090871809:ios:4f085b112b9c2e4532e800',
    messagingSenderId: '1040090871809',
    projectId: 'widget-of-the-week',
    storageBucket: 'widget-of-the-week.appspot.com',
    iosBundleId: 'com.example.widgetOfTheWeek.RunnerTests',
  );
}
